<a href="https://colab.research.google.com/github/jayasriponali/masai/blob/main/task3_train_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [259]:
!pip3 install pandas

!pip3 install scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [301]:
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

from sklearn.metrics import classification_report

In [261]:
df = pd.read_csv("/content/churnguard_data (3).csv")
df

,customerID,gender,SeniorCitizen,tenure,PhoneService,InternetService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST-0032,Male,0,21.0,YES,Fiber optic,Month-to-month,No,Credit card,29.73,600.01,Yes
1,CUST-0110,Male,0,55.0,YES,Fiber optic,Two year,Yes,Bank transfer,46.32,2515.48,No
2,CUST-0137,Female,1,46.0,Yes,Fiber optic,Month-to-month,No,Mailed check,87.06,4153.97,Yes
3,CUST-0089,Female,1,63.0,Yes,Fiber optic,Month-to-month,YES,Mailed check,56.97,3641.3,Yes
4,CUST-0919,Female,0,8.0,Yes,DSl,month to month,No,Electronic check,39.69,309.79,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
1025,CUST-0088,Female,0,26.0,Yes,DSL,One year,Yes,Electronic check,51.68,1369.73,No
1026,CUST-0331,Male,0,49.0,Yes,Fiber optic,Two year,Yes,Electronic check,85.39,4305.4,No
1027,CUST-0467,Male,1,69.0,Yes,DSl,Two year,Yes,Electronic check,95.00,6689.62,No
1028,CUST-0122,Female,1,3.0,Yes,No,Two year,Yes,Electronic check,25.08,77.2,No
1029,CUST-0861,Female,0,49.0,Yes,DSL,month-to-month,No,Credit card,103.84,5307.47,No

In [262]:
df.drop(['customerID'],axis = 1,inplace = True)

In [263]:
df

,gender,SeniorCitizen,tenure,PhoneService,InternetService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Male,0,21.0,YES,Fiber optic,Month-to-month,No,Credit card,29.73,600.01,Yes
1,Male,0,55.0,YES,Fiber optic,Two year,Yes,Bank transfer,46.32,2515.48,No
2,Female,1,46.0,Yes,Fiber optic,Month-to-month,No,Mailed check,87.06,4153.97,Yes
3,Female,1,63.0,Yes,Fiber optic,Month-to-month,YES,Mailed check,56.97,3641.3,Yes
4,Female,0,8.0,Yes,DSl,month to month,No,Electronic check,39.69,309.79,Yes
...,...,...,...,...,...,...,...,...,...,...,...
1025,Female,0,26.0,Yes,DSL,One year,Yes,Electronic check,51.68,1369.73,No
1026,Male,0,49.0,Yes,Fiber optic,Two year,Yes,Electronic check,85.39,4305.4,No
1027,Male,1,69.0,Yes,DSl,Two year,Yes,Electronic check,95.00,6689.62,No
1028,Female,1,3.0,Yes,No,Two year,Yes,Electronic check,25.08,77.2,No
1029,Female,0,49.0,Yes,DSL,month-to-month,No,Credit card,103.84,5307.47,No

In [264]:
df.drop_duplicates(inplace = True)

In [265]:
df[['gender','PaymentMethod']] = df[['gender','PaymentMethod']].apply(lambda x : x.str.strip())

In [266]:
df[['Churn','PhoneService','PaperlessBilling']] = df[['Churn','PhoneService','PaperlessBilling']].apply(lambda x : x.str.strip().str.title())

In [267]:
df['Contract'].unique()

array(['Month-to-month', 'Two year', 'month to month', 'One year',
       'month-to-month', 'Monthly', 'Two Year', '1 year', '2 year',
       'two year', 'One Year', 'one year'], dtype=object)

In [268]:
contract_map = {
    'Month-to-month':'Month-to-month',
    'Two year':'Two year',
    'month to month': 'Month-to-month',
    'One year': 'One year',
    'month-to-month': 'Month-to-month',
    'Monthly': 'Month-to-month',
    'Two Year': 'Two year',
    '1 year': 'One year',
    '2 year': 'Two year',
    'two year': 'Two year',
    'One Year': 'One year',
    'one year': 'One year'
}

In [269]:
df['Contract'] = df['Contract'].map(contract_map).values
df['Contract']

0       Month-to-month
1             Two year
2       Month-to-month
3       Month-to-month
4       Month-to-month
             ...
1025          One year
1026          Two year
1027          Two year
1028          Two year
1029    Month-to-month
Name: Contract, Length: 1000, dtype: object

In [270]:
df['InternetService'].unique()

array(['Fiber optic', 'DSl', 'DSL', 'dsl', 'No', 'fiber optic',
       'FiberOptic', 'Fibre optic', 'Dsl', 'NO', nan, 'no'], dtype=object)

In [271]:
InternetService_map = {
   'Fiber optic': 'Fiber optic',
    'DSl': 'DSL',
   'DSL': 'DSL',
    'dsl': 'DSL',
    'No': 'No',
   'fiber optic': 'Fiber optic',
   'FiberOptic': 'Fiber optic',
    'Fibre optic':'Fiber optic',
   'Dsl': 'DSL',
    'NO': 'No',
   'nan': 'No',
    'no': 'No'
}

In [272]:
df['InternetService'] = df['InternetService'].map(InternetService_map).fillna('No')
df['InternetService']

0       Fiber optic
1       Fiber optic
2       Fiber optic
3       Fiber optic
4               DSL
           ...
1025            DSL
1026    Fiber optic
1027            DSL
1028             No
1029            DSL
Name: InternetService, Length: 1000, dtype: object

In [273]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'],errors = 'coerce')

In [274]:
df = df[df['tenure'] > 0]
df

,gender,SeniorCitizen,tenure,PhoneService,InternetService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Male,0,21.0,Yes,Fiber optic,Month-to-month,No,Credit card,29.73,600.01,Yes
1,Male,0,55.0,Yes,Fiber optic,Two year,Yes,Bank transfer,46.32,2515.48,No
2,Female,1,46.0,Yes,Fiber optic,Month-to-month,No,Mailed check,87.06,4153.97,Yes
3,Female,1,63.0,Yes,Fiber optic,Month-to-month,Yes,Mailed check,56.97,3641.30,Yes
4,Female,0,8.0,Yes,DSL,Month-to-month,No,Electronic check,39.69,309.79,Yes
...,...,...,...,...,...,...,...,...,...,...,...
1025,Female,0,26.0,Yes,DSL,One year,Yes,Electronic check,51.68,1369.73,No
1026,Male,0,49.0,Yes,Fiber optic,Two year,Yes,Electronic check,85.39,4305.40,No
1027,Male,1,69.0,Yes,DSL,Two year,Yes,Electronic check,95.00,6689.62,No
1028,Female,1,3.0,Yes,No,Two year,Yes,Electronic check,25.08,77.20,No
1029,Female,0,49.0,Yes,DSL,Month-to-month,No,Credit card,103.84,5307.47,No

In [275]:
df = df[(df['MonthlyCharges'] > 10) & (df['MonthlyCharges'] < 200)]
df

,gender,SeniorCitizen,tenure,PhoneService,InternetService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Male,0,21.0,Yes,Fiber optic,Month-to-month,No,Credit card,29.73,600.01,Yes
1,Male,0,55.0,Yes,Fiber optic,Two year,Yes,Bank transfer,46.32,2515.48,No
2,Female,1,46.0,Yes,Fiber optic,Month-to-month,No,Mailed check,87.06,4153.97,Yes
3,Female,1,63.0,Yes,Fiber optic,Month-to-month,Yes,Mailed check,56.97,3641.30,Yes
4,Female,0,8.0,Yes,DSL,Month-to-month,No,Electronic check,39.69,309.79,Yes
...,...,...,...,...,...,...,...,...,...,...,...
1025,Female,0,26.0,Yes,DSL,One year,Yes,Electronic check,51.68,1369.73,No
1026,Male,0,49.0,Yes,Fiber optic,Two year,Yes,Electronic check,85.39,4305.40,No
1027,Male,1,69.0,Yes,DSL,Two year,Yes,Electronic check,95.00,6689.62,No
1028,Female,1,3.0,Yes,No,Two year,Yes,Electronic check,25.08,77.20,No
1029,Female,0,49.0,Yes,DSL,Month-to-month,No,Credit card,103.84,5307.47,No

In [276]:
df['MonthlyCharges'] = df['MonthlyCharges'].fillna(df['MonthlyCharges'].mean())

/tmp/ipykernel_6007/1821109709.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['MonthlyCharges'] = df['MonthlyCharges'].fillna(df['MonthlyCharges'].mean())

In [277]:
df['TotalCharges'] =  df['TotalCharges'].fillna(df['TotalCharges'].mean())

/tmp/ipykernel_6007/1953819416.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TotalCharges'] =  df['TotalCharges'].fillna(df['TotalCharges'].mean())

In [278]:
df['tenure'] = df['tenure'].fillna(round(df['tenure'].median(),2))

/tmp/ipykernel_6007/2388605195.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tenure'] = df['tenure'].fillna(round(df['tenure'].median(),2))

In [279]:
print(f" shape of the cleaned DataFrame {df.shape}")

 shape of the cleaned DataFrame (867, 11)

In [280]:
print(f"missing value counts {df.isna().sum().sum()}")

missing value counts 0

In [281]:
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

/tmp/ipykernel_6007/4069049957.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

In [283]:
df = pd.get_dummies(df,['gender', 'PhoneService', 'InternetService', 'Contract', 'PaperlessBilling', 'PaymentMethod'],drop_first = True)

In [287]:
X = df.drop(['Churn'],axis=1)
y = df['Churn']

In [290]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size = 0.80,random_state = 42)

In [291]:
model = LogisticRegression(max_iter = 1000)

In [292]:
model.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [294]:
y_pred = model.predict(X_test)

In [300]:
print(f" accuracy score {accuracy_score(y_test,y_pred): .2f}")

 accuracy score  0.70

In [302]:
target_names = ['Stay', 'Churn']
print(classification_report(y_test,y_pred,target_names = target_names))

              precision    recall  f1-score   support

        Stay       0.75      0.85      0.80       122
       Churn       0.50      0.35      0.41        52

    accuracy                           0.70       174
   macro avg       0.63      0.60      0.60       174
weighted avg       0.68      0.70      0.68       174