<a href="https://colab.research.google.com/github/jayasriponali/masai/blob/main/task4_predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [329]:
!pip3 install pandas

!pip3 install scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [330]:
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

from sklearn.metrics import classification_report

In [331]:
df = pd.read_csv("/content/churnguard_data (4).csv")
df

,customerID,gender,SeniorCitizen,tenure,PhoneService,InternetService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST-0032,Male,0,21.0,YES,Fiber optic,Month-to-month,No,Credit card,29.73,600.01,Yes
1,CUST-0110,Male,0,55.0,YES,Fiber optic,Two year,Yes,Bank transfer,46.32,2515.48,No
2,CUST-0137,Female,1,46.0,Yes,Fiber optic,Month-to-month,No,Mailed check,87.06,4153.97,Yes
3,CUST-0089,Female,1,63.0,Yes,Fiber optic,Month-to-month,YES,Mailed check,56.97,3641.3,Yes
4,CUST-0919,Female,0,8.0,Yes,DSl,month to month,No,Electronic check,39.69,309.79,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
1025,CUST-0088,Female,0,26.0,Yes,DSL,One year,Yes,Electronic check,51.68,1369.73,No
1026,CUST-0331,Male,0,49.0,Yes,Fiber optic,Two year,Yes,Electronic check,85.39,4305.4,No
1027,CUST-0467,Male,1,69.0,Yes,DSl,Two year,Yes,Electronic check,95.00,6689.62,No
1028,CUST-0122,Female,1,3.0,Yes,No,Two year,Yes,Electronic check,25.08,77.2,No
1029,CUST-0861,Female,0,49.0,Yes,DSL,month-to-month,No,Credit card,103.84,5307.47,No

In [332]:
df.drop(['customerID'],axis = 1,inplace = True)

In [333]:
df.drop_duplicates(inplace = True)

In [334]:
df[['gender','PaymentMethod']] = df[['gender','PaymentMethod']].apply(lambda x : x.str.strip())

In [335]:
df[['Churn','PhoneService','PaperlessBilling']] = df[['Churn','PhoneService','PaperlessBilling']].apply(lambda x : x.str.strip().str.title())

In [336]:
contract_map = {
    'Month-to-month':'Month-to-month',
    'Two year':'Two year',
    'month to month': 'Month-to-month',
    'One year': 'One year',
    'month-to-month': 'Month-to-month',
    'Monthly': 'Month-to-month',
    'Two Year': 'Two year',
    '1 year': 'One year',
    '2 year': 'Two year',
    'two year': 'Two year',
    'One Year': 'One year',
    'one year': 'One year'
}

In [337]:
df['Contract'] = df['Contract'].map(contract_map).values
df['Contract']

0       Month-to-month
1             Two year
2       Month-to-month
3       Month-to-month
4       Month-to-month
             ...
1025          One year
1026          Two year
1027          Two year
1028          Two year
1029    Month-to-month
Name: Contract, Length: 1000, dtype: object

In [338]:
InternetService_map = {
   'Fiber optic': 'Fiber optic',
    'DSl': 'DSL',
   'DSL': 'DSL',
    'dsl': 'DSL',
    'No': 'No',
   'fiber optic': 'Fiber optic',
   'FiberOptic': 'Fiber optic',
    'Fibre optic':'Fiber optic',
   'Dsl': 'DSL',
    'NO': 'No',
   'nan': 'No',
    'no': 'No'
}

In [339]:
df['InternetService'] = df['InternetService'].map(InternetService_map).fillna('No')
df['InternetService']

0       Fiber optic
1       Fiber optic
2       Fiber optic
3       Fiber optic
4               DSL
           ...
1025            DSL
1026    Fiber optic
1027            DSL
1028             No
1029            DSL
Name: InternetService, Length: 1000, dtype: object

In [340]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'],errors = 'coerce')

In [341]:
df = df[df['tenure'] > 0]
df

,gender,SeniorCitizen,tenure,PhoneService,InternetService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Male,0,21.0,Yes,Fiber optic,Month-to-month,No,Credit card,29.73,600.01,Yes
1,Male,0,55.0,Yes,Fiber optic,Two year,Yes,Bank transfer,46.32,2515.48,No
2,Female,1,46.0,Yes,Fiber optic,Month-to-month,No,Mailed check,87.06,4153.97,Yes
3,Female,1,63.0,Yes,Fiber optic,Month-to-month,Yes,Mailed check,56.97,3641.30,Yes
4,Female,0,8.0,Yes,DSL,Month-to-month,No,Electronic check,39.69,309.79,Yes
...,...,...,...,...,...,...,...,...,...,...,...
1025,Female,0,26.0,Yes,DSL,One year,Yes,Electronic check,51.68,1369.73,No
1026,Male,0,49.0,Yes,Fiber optic,Two year,Yes,Electronic check,85.39,4305.40,No
1027,Male,1,69.0,Yes,DSL,Two year,Yes,Electronic check,95.00,6689.62,No
1028,Female,1,3.0,Yes,No,Two year,Yes,Electronic check,25.08,77.20,No
1029,Female,0,49.0,Yes,DSL,Month-to-month,No,Credit card,103.84,5307.47,No

In [342]:
df = df[(df['MonthlyCharges'] > 10) & (df['MonthlyCharges'] < 200)]
df

,gender,SeniorCitizen,tenure,PhoneService,InternetService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Male,0,21.0,Yes,Fiber optic,Month-to-month,No,Credit card,29.73,600.01,Yes
1,Male,0,55.0,Yes,Fiber optic,Two year,Yes,Bank transfer,46.32,2515.48,No
2,Female,1,46.0,Yes,Fiber optic,Month-to-month,No,Mailed check,87.06,4153.97,Yes
3,Female,1,63.0,Yes,Fiber optic,Month-to-month,Yes,Mailed check,56.97,3641.30,Yes
4,Female,0,8.0,Yes,DSL,Month-to-month,No,Electronic check,39.69,309.79,Yes
...,...,...,...,...,...,...,...,...,...,...,...
1025,Female,0,26.0,Yes,DSL,One year,Yes,Electronic check,51.68,1369.73,No
1026,Male,0,49.0,Yes,Fiber optic,Two year,Yes,Electronic check,85.39,4305.40,No
1027,Male,1,69.0,Yes,DSL,Two year,Yes,Electronic check,95.00,6689.62,No
1028,Female,1,3.0,Yes,No,Two year,Yes,Electronic check,25.08,77.20,No
1029,Female,0,49.0,Yes,DSL,Month-to-month,No,Credit card,103.84,5307.47,No

In [343]:
df['MonthlyCharges'] = df['MonthlyCharges'].fillna(df['MonthlyCharges'].mean())

/tmp/ipykernel_15982/1821109709.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['MonthlyCharges'] = df['MonthlyCharges'].fillna(df['MonthlyCharges'].mean())

In [344]:
df['TotalCharges'] =  df['TotalCharges'].fillna(df['TotalCharges'].mean())

/tmp/ipykernel_15982/1953819416.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TotalCharges'] =  df['TotalCharges'].fillna(df['TotalCharges'].mean())

In [345]:
df['tenure'] = df['tenure'].fillna(round(df['tenure'].median(),2))

/tmp/ipykernel_15982/2388605195.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tenure'] = df['tenure'].fillna(round(df['tenure'].median(),2))

In [346]:
print(f" shape of the cleaned DataFrame {df.shape}")

 shape of the cleaned DataFrame (867, 11)

In [347]:
print(f"missing value counts {df.isna().sum().sum()}")

missing value counts 0

In [348]:
X = df.drop(['Churn'],axis=1)
y = df['Churn']

In [349]:
contract_map = {
    'Month-to-month':'Month-to-month',
    'Two year':'Two year',
    'month to month': 'Month-to-month',
    'One year': ' One year',
    'month-to-month': 'Month-to-month',
    'Monthly': 'Month-to-month',
    'Two Year': 'Two year',
    '1 year': ' One year',
    '2 year': 'Two year',
    'two year': ' Two year',
    'One Year': 'One year',
    'one year': 'One year'
}

df['Contract'] = df['Contract'].map(contract_map).values
df['Contract']

df['InternetService'].unique()

InternetService_map = {
   'Fiber optic': 'Fiber optic',
    'DSl': 'DSL',
   'DSL': 'DSL',
    'dsl': 'DSL',
    'No': 'No',
   'fiber optic': 'Fiber optic',
   'FiberOptic': ' Fiber optic',
    'Fibre optic':' Fiber optic',
   'Dsl': 'DSL',
    'NO': 'No',
   'nan': 'No',
    'no': 'No'
}

df['InternetService'] = df['InternetService'].map(InternetService_map).fillna('No')


df['TotalCharges'] = pd.to_numeric(df['TotalCharges'],errors = 'coerce')
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

df = pd.get_dummies(df,['gender', 'PhoneService', 'InternetService', 'Contract', 'PaperlessBilling', 'PaymentMethod'],drop_first = True)

X = df.drop(['Churn'],axis=1)
y = df['Churn']

/tmp/ipykernel_15982/2017620172.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Contract'] = df['Contract'].map(contract_map).values
/tmp/ipykernel_15982/2017620172.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['InternetService'] = df['InternetService'].map(InternetService_map).fillna('No')
/tmp/ipykernel_15982/2017620172.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TotalCharges'] = pd.to_numeric(df['TotalCharges'],errors = 'coerce')
/tmp/ipykernel_15982/2017620172.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

In [351]:
model = LogisticRegression()
model.fit(X,y)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [352]:
tenure = int(input("Enter tenure (months):"))

Enter tenure (months):1

In [353]:
MonthlyCharges = float(input("Enter Monthly Charges:"))

Enter Monthly Charges:1

In [354]:
TotalCharges = float(input("Enter Total Charges:"))

Enter Total Charges:1

In [355]:
SeniorCitizen =int(input("Senior Citizen? (1 = Yes, 0 = No):"))

Senior Citizen? (1 = Yes, 0 = No):1

In [356]:
Contract = int(input("Contract type (0 = Month-to-month, 1 = One year, 2 = Two year):"))

Contract type (0 = Month-to-month, 1 = One year, 2 = Two year):1

In [357]:
Contract_Month_to_month=False
Contract_One_year=False
Contract_Two_year=False
if Contract == 0:
  Contract_Month_to_month = True
elif Contract == 1:
  Contract_One_year = True
elif Contract == 2:
  Contract_Two_year = True

In [358]:
data = {
     "SeniorCitizen":SeniorCitizen,
    "tenure": tenure,
    "MonthlyCharges":MonthlyCharges,
    "TotalCharges":TotalCharges,
    "gender_Male":False,
     "PhoneService_Yes":False,
         "InternetService_Fiber optic": False,
         "InternetService_No":False,
    "Contract_Month-to-month": Contract_Month_to_month,
    "Contract_Two year":Contract_Two_year,
    "PaperlessBilling_Yes":False,
    "PaymentMethod_Credit card":False,
    "PaymentMethod_Electronic check":False,
    "PaymentMethod_Mailed check":False

}

data

{'SeniorCitizen': 1,
 'tenure': 1,
 'MonthlyCharges': 1.0,
 'TotalCharges': 1.0,
 'gender_Male': False,
 'PhoneService_Yes': False,
 'InternetService_Fiber optic': False,
 'InternetService_No': False,
 'Contract_Month-to-month': False,
 'Contract_Two year': False,
 'PaperlessBilling_Yes': False,
 'PaymentMethod_Credit card': False,
 'PaymentMethod_Electronic check': False,
 'PaymentMethod_Mailed check': False}

In [359]:
df_new = pd.DataFrame(data,  index=[0])

In [361]:
df_new

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,PhoneService_Yes,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card,PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1,1,1.0,1.0,False,False,False,False,False,False,False,False,False,False

In [362]:
y_pred = model.predict(df_new)

In [363]:
print(f"This is the final answer : {y_pred}")

This is the final answer : [0]